CREATE TABLE tb_user (
    ID_CUSTOMER UUID PRIMARY KEY,
    COD_CUSTOMER VARCHAR(200) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(150),
    SAFEPAY_USER BIGINT NOT NULL,
    CREDIT_FLAG BOOLEAN NOT NULL,
    ACCOUNT_FLAG BOOLEAN,
    PREPAID_FLAG BOOLEAN,
    CREATION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CPF VARCHAR(11)
);